### ISSUE TITLE
Netlify Build: [nuxt:auto-imports-transform] [unimport] failed to find "createSanityClient" imported from "#imports"

### ISSUE THREAD

**Issue by MichaelPrecel** [nuxt-modules/sanity#502]
### Version
module: ^1.2.3
nuxt: 3.0.0-rc.6

### Nuxt configuration
nuxt.config.ts includes `modules: ["@nuxtjs/sanity"]` and sanity projectId and apiVersion

### What is happening
On attempting to build the project in Netlify, I'm receiving the following error preventing the build from completing. This isn't being repoduced in either dev or local `build` or `generate` commands, only once in Netlify.

```
4:25:05 PM: > nuxt build
4:25:05 PM: [log] Nuxt CLI v3.0.0-rc.8
4:25:11 PM: [info] [@nuxtjs/sanity] Enabling minimal client as @sanity/client is not installed.
4:25:11 PM: [info] [@nuxtjs/sanity] Running with Sanity project XXXXXX (production).
4:25:15 PM: [error] [nuxt:auto-imports-transform] [unimport] failed to find "createSanityClient" imported from "#imports"
4:25:15 PM: file: /opt/build/repo/nuxt/node_modules/@nuxtjs/sanity/dist/runtime/composables.mjs
4:25:15 PM: [error] [unimport] failed to find "createSanityClient" imported from "#imports"
4:25:15 PM:   at node_modules/unimport/dist/chunks/context.mjs:716:17
4:25:15 PM:   at Array.forEach (<anonymous>)
4:25:15 PM:   at node_modules/unimport/dist/chunks/context.mjs:713:44
4:25:15 PM:   at Array.forEach (<anonymous>)
4:25:15 PM:   at detectImports (node_modules/unimport/dist/chunks/context.mjs:711:20)
4:25:15 PM:   at injectImports (node_modules/unimport/dist/chunks/context.mjs:738:50)
4:25:15 PM:   at async Object.transform (node_modules/nuxt/dist/index.mjs:885:21)
```

Because I have successfully built and deployed a Nuxt 3 project with the Sanity helper previously, I tried rolling back to RC4 and recieved the error worded slightly differently.

```
4:53:45 PM: [error] 'createSanityClient' is not exported by virtual:nuxt:/opt/build/repo/nuxt/.nuxt/imports.mjs, imported by node_modules/@nuxtjs/sanity/dist/runtime/composables.mjs
4:53:45 PM: file: /opt/build/repo/nuxt/node_modules/@nuxtjs/sanity/dist/runtime/composables.mjs:3:0
4:53:45 PM: 1: import { defu } from "defu";
4:53:45 PM: 2: import { objectHash } from "ohash";
4:53:45 PM: 3: import { useNuxtApp, useRuntimeConfig, useAsyncData, useLazyAsyncData, createSanityClient } from "#imports";
4:53:45 PM:    ^
4:53:45 PM: 4: const createSanityHelper = (options) => {
4:53:45 PM: 5:   const config = options;
4:53:45 PM: [error] 'createSanityClient' is not exported by virtual:nuxt:/opt/build/repo/nuxt/.nuxt/imports.mjs, imported by node_modules/@nuxtjs/sanity/dist/runtime/composables.mjs
```

Any idea what might be causing this?

**Comment by danielroe** [comment]
This is definitely odd. Would you provide a reproduction? 🙏

**Comment by MichaelPrecel** [comment]
Hi @danielroe thanks for getting back to me here—it was my silly oversight. I needed to set the Node environment in Netlify so it didn't fall back to v12! 🤯
