### ISSUE TITLE
Enable `groq` in server routes

### ISSUE THREAD

**Issue by safejace** [nuxt-modules/sanity#503]
### Is your feature request related to a problem? Please describe.
Trying to call `groq` in a server route throws an error

### Describe the solution you'd like to see
Include `groq` in server route files

### Describe alternatives you've considered
n/a

### Additional context
when trying to use `groq` in `./server/routes/test.ts` i get this error
```
[nuxt] [request error] [unhandled] [500] groq is not defined
  at ./.nuxt/dev/index.mjs:464:17  
  at ./node_modules/h3/dist/index.mjs:377:14  
  at Object.handler (./node_modules/h3/dist/index.mjs:584:12)  
  at ./node_modules/h3/dist/index.mjs:492:31  
  at processTicksAndRejections (node:internal/process/task_queues:96:5)  
  at async Server.nodeHandler (./node_modules/h3/dist/index.mjs:438:7)
  ```

**Comment by safejace** [comment]
when i use just a string as a query, now it says

```
[nuxt] [request error] [unhandled] [500] useSanityQuery is not defined
  at ./.nuxt/dev/index.mjs:470:20  
  ```
i think i am missing something here. do the server routes not have things auto imported like in other nuxt files?
