### ISSUE TITLE
Support nuxt 3.0.0-rc.14

### ISSUE THREAD

**Issue by svnldwg** [nuxt-modules/sanity#561]
### Is your feature request related to a problem? Please describe.
Nuxt 3.0.0-rc.14 (the last RC before the official release) was just released. I tried to update it in my project, but @nuxt/sanity seems to be not compatible with it yet. I get this error message when starting up Nuxt:

```
ERROR  Cannot restart nuxt:  Cannot read properties of undefined (reading 'sanity')                                                            08:54:52

  at setup (node_modules/@nuxtjs/sanity/dist/module.mjs:50:118)
  at normalizedModule (node_modules/@nuxt/kit/dist/index.mjs:642:29)
  at async installModule (node_modules/nuxt/node_modules/@nuxt/kit/dist/index.mjs:416:3)
  at async initNuxt (node_modules/nuxt/dist/index.mjs:1827:7)
  at async load (node_modules/nuxi/dist/chunks/dev.mjs:6779:9)
  at async _applyPromised (node_modules/nuxi/dist/chunks/dev.mjs:6713:10)
```

### Describe the solution you'd like to see
Support Nuxt3 RC14 to be ready for the official release of Nuxt3.

### Additional context
Release Notes of Nuxt 3 RC14: https://github.com/nuxt/framework/releases/tag/v3.0.0-rc.14

**Comment by danielroe** [comment]
That's really kind of you! You can always sponsor [Nuxt itself](https://github.com/sponsors/nuxt) - or, if you would like, [me](https://github.com/sponsors/danielroe) or any of the other [contributors](https://github.com/nuxt-modules/sanity/graphs/contributors).

**Comment by danielroe** [comment]
... and thanks for the report. It's an upstream issue - will be resolved in https://github.com/nuxt/framework/pull/9050.
